apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convai-finance-agentic-rag.fullname" . }}-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.secrets.OPENAI_API_KEY }}"
  TAVILY_API_KEY: "{{ .Values.secrets.TAVILY_API_KEY }}"
  DATABASE_URL: "{{ .Values.secrets.DATABASE_URL }}"
