apiVersion: v1
kind: Service
metadata:
  name: {{ include "convai-finance-agentic-rag.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: rag-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
