# kustomize build deploy/k8s | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: convai-rag
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-example.yaml
  - redis.yaml
  - postgres.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - hpa-api.yaml
  - ingress.yaml
